// src/app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import Login from "./components/login";
import "./globals.css";
import SessionProviderWrapper from "./components/SessionProviderWrapper";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
        <Login/>
          {children}
          </SessionProviderWrapper>
      </body>
    </html>
  );
}
